url: https://morningfisho.github.io/morningfish/
baseurl: /morningfish/

# Site settings
title: Katelyn Mak
email: katelyn_mak@myabcusd.org
description: "test test"
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/morningfisho

# Postal address (add as many lines as necessary)
address:
  - line: Los Angeles, CA

# Build settings
markdown: kramdown
permalink: pretty
